### DISCUSSION TITLE
Edit your favicon

### DISCUSSION THREAD

**Discussion by Kourtney-Burger** [nmfs-ost/PAM-OpenScience#30] [Tips and Tricks]
@jlkeating

Hi Jennifer, can you share how you updated your favicon on the PIFSC PAM Lab Manual? Thanks!

**Comment by jlkeating** [comment]
1. Select an image (best results are square or circle)
2. Follow the instructions on this [website](https://www.lcn.com/blog/beginners-guide-favicons/).
3. Download the favicon image
4. Paste in folder within your repository and link it in the yml.

Example code:

website: 
  page-navigation: true
  title: "CRP-PAM Lab Manual" 
  site-url: "https://pifsc-protected-species-division.github.io/CRP_PAM_Manual/" 
  repo-url: "https://github.com/PIFSC-Protected-Species-Division/CRP_PAM_Manual"
  repo-actions: [edit, source, issue]
  favicon: content/images/favicon.ico

**Comment by sfregosi-noaa** [comment]
@Kourtney-Burger To add to this - the favicon image file does not actually have to be called favicon.ico. You can just point to any small, ideally square image you have saved in a repository. For example, on the PAM-Glider site I just used the SEAGLIDER.PNG that was already in the `content/images` folder. 

You can see the `_quarto.yaml` here and it's on Line 10: [https://github.com/nmfs-ost/PAM-Glider/blob/main/_quarto.yml](https://github.com/nmfs-ost/PAM-Glider/blob/main/_quarto.yml)

```
website: 
  page-navigation: true
  title: "PAM-UxS" 
  site-url: "https://nmfs-pam-glider.github.io/PAM-UxS/" 
  repo-url: "https://github.com/NMFS-PAM-Glider/PAM-UxS"
  repo-actions: [edit, source, issue]
  favicon: content/images/SEAGLIDER.png
```
